CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)        UNIQUE              NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
    );
CREATE TABLE IF NOT EXISTS category
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)   UNIQUE             NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id) );

CREATE TABLE IF NOT EXISTS location(
     id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     lat FLOAT NOT NULL,
     lon FLOAT NOT NULL
);



CREATE TABLE IF NOT EXISTS events (
   id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   annotation  VARCHAR(4096)                            NOT NULL,
   category_id INTEGER                                 NOT NULL,
   description VARCHAR(8192)                            NOT NULL,
   event_date timestamp without time zone,
   lat FLOAT NOT NULL,
   lon FLOAT NOT NULL,
   paid boolean                                 NOT NULL,
   participant_limit INTEGER               NOT NULL,
   request_moderation boolean         NOT NULL,
   title VARCHAR(255)                            NOT NULL,
   created_on timestamp without time zone,
   published_on timestamp without time zone,
   user_id INTEGER                                 NOT NULL,
   state VARCHAR(255)                            NOT NULL,
   FOREIGN KEY (category_id) references category (id),
   FOREIGN KEY (user_id) references users (id)
);
CREATE TABLE IF NOT EXISTS requests(
  id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created timestamp without time zone,
  event  INTEGER         NOT NULL,
  requester  INTEGER         NOT NULL,
  status VARCHAR(255)                            NOT NULL
);
CREATE TABLE IF NOT EXISTS compilations(
         id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      pinned boolean         NOT NULL,
       title  VARCHAR(255)                            NOT NULL
);

CREATE TABLE IF NOT EXISTS eventIdsForCompilation(
  id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  compilation_id integer not null,
  event_id integer not null
);



