version: '3.1'
services:
  stats-server:
    build: stat/stat-server
    image: ewm-stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
     - stats-db
    environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat
  stats-db:
    image: postgres:14-alpine
    container_name: postgres-ewm-stats-db
    ports:
      - "6541:5432"
    environment:
        - POSTGRES_DB=stat
        - POSTGRES_USER=stat
        - POSTGRES_PASSWORD=1234

  ewm-service:
   build: main-service
   image: ewm-main-service
   container_name: ewm-main-service
   ports:
      - "8080:8080"
   depends_on:
     - stats-server
     - ewm-db
   environment:
   - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/db

  ewm-db:
    image: postgres:14-alpine
    container_name: postgres-ewm-main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234