version: '3.1'
services:
  stats-server:
    build: stat/stat-server
    image: stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
     - stats-db
    environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
        - POSTGRES_DB=stat
        - POSTGRES_USER=stat
        - POSTGRES_PASSWORD=1234

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
