CREATE TABLE IF NOT EXISTS stat
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app  VARCHAR(255)                            NOT NULL,
    uri VARCHAR(512)                            NOT NULL,
    ip VARCHAR(512)                            NOT NULL,
    created timestamp without time zone
    );





